// <auto-generated />
using System;
using Julio.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Julio.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20240510142334_Folha")]
    partial class Folha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Julio.Models.Folha", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ano")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("mes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Folha");
                });

            modelBuilder.Entity("Julio.Models.Funcionario", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
